package trabalhopratico;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aeroportos.java
//  @ Date : 15/11/2014
//  @ Author : Robson
//
//
public class Aeroportos {
	private Integer codAeroport;
	private String nmAeroport;
	private String localAeroport;
/**
 * Método que retorna o Código do Aeroporto.
 * @return 
 */	
        public Integer getCodAeroport() {
	return codAeroport;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Código do Aeroporto.
 * @param codAeroport 
 */	
	public void setCodAeroport(Integer codAeroport) {
	this.codAeroport = codAeroport;
	}
/**
 * Método que retorna o nome do Aeroporto.
 * @return 
 */	
	public String getNmAeroport() {
	return nmAeroport;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Nome do Aeroporto.
 * @param nmAeroport 
 */	
	public void setNmAeroport(String nmAeroport) {
	this.nmAeroport = nmAeroport;
	}
/**
 * Método que retorna o Local do Aeroporto.
 * @return 
 */	
	public String getLocalAeroport() {
	return localAeroport;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Local do Aeroporto.
 * @param localAeroport 
 */	
	public void setLocalAeroport(String localAeroport) {
	this.localAeroport = localAeroport;
	}
}
