package trabalhopratico;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AeroportOrigem.java
//  @ Date : 15/11/2014
//  @ Author : Robson
//
//
public class AeroportOrigem extends Aeroportos {
}
