package trabalhopratico;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AeroportDestino.java
//  @ Date : 15/11/2014
//  @ Author : Robson
//
//
public class AeroportDestino extends Aeroportos {
}
