package trabalhopratico;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Atendente.java
//  @ Date : 15/11/2014
//  @ Author : Robson
//
//
public class Atendente extends Pessoa {
}
