package trabalhopratico;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 15/11/2014
//  @ Author : Robson
//
//

public class Cliente extends Pessoa {
	private ReservaViagem reservaViagem;
/**
 * Método que retorna a Reserva de Viagem.
 * @return 
 */	
        public ReservaViagem getReservaViagem() {
	return reservaViagem;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Reserva de Viagem.
 * @param reservaViagem 
 */	
	public void setReservaViagem(ReservaViagem reservaViagem) {
	this.reservaViagem = reservaViagem;
        }
}
