package trabalhopratico;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Agência Aerea 
//  @ File Name : DescAviao.java
//  @ Date : 15/11/2014
//  @ Author : Robson
//
//
public class DescAviao {
	private String nmFabr;
	private Integer numModelo;
	private Integer numAssentos;
/**
 * Método que retorna o Nome do Fabricante.
 * @return 
 */	
        public String getNmFabr() {
	return nmFabr;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Nome do Fabricante.
 * @param nmFabr 
 */	
	public void setNmFabr(String nmFabr) {
	this.nmFabr = nmFabr;
	}
/**
 * Método que retorna o número do modelo.
 * @return 
 */	
	public Integer getNumModelo() {
	return numModelo;
	}
/**
 *  Método que permite o acesso de outras classes ao atributo Número do Modelo.
 * @param numModelo 
 */	
	public void setNumModelo(Integer numModelo) {
	this.numModelo = numModelo;
	}
/**
 * Método que retorna o Número de Assentos.
 * @return 
 */	
	public Integer getNumAssentos() {
	return numAssentos;
	}
/**
 *  Método que permite o acesso de outras classes ao atributo Número de Assentos.
 * @param numAssentos 
 */	
	public void setNumAssentos(Integer numAssentos) {
	this.numAssentos = numAssentos;
	}
}
