package trabalhopratico;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pessoa.java
//  @ Date : 15/11/2014
//  @ Author : Robson
//
//
public class Pessoa {
	private String nome;
	private Integer cpf;
	private String end;
	private Integer tel;
/**
 * Método que retorna o Nome.
 * @return 
 */	
        public String getNome() {
	return nome;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Nome.
 * @param nome 
 */	
	public void setNome(String nome) {
	this.nome = nome;
	}
/**
 * Método que retorna o Cpf.
 * @return 
 */	
	public Integer getCpf() {
	return cpf;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Cpf.
 * @param cpf 
 */	
	public void setCpf(Integer cpf) {
	this.cpf = cpf;
	}
/**
 * Método que retorna o Endereço.
 * @return 
 */	
	public String getEnd() {
	return end;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Endereço.
 * @param end 
 */	
	public void setEnd(String end) {
	this.end = end;
	}
/**
 * Método que retorna o telefone.
 * @return 
 */	
	public Integer getTel() {
	return tel;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Telefone.
 * @param tel 
 */	
	public void setTel(Integer tel) {
	this.tel = tel;
	}
}
