 package trabalhopratico;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReservaVoo.java
//  @ Date : 15/11/2014
//  @ Author : Robson
//
//
public class ReservaVoo {
	private Voo voo;
	private Integer codReservaVoo;
	private Integer numReservas;
/**
 * Método que retorna o Voo.
 * @return 
 */	
        public Voo getvoo() {
	return voo;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Voo.
 * @param voo 
 */	
	public void setVoo(Voo voo) {
	this.voo = voo;
	}
/**
 * Método que retorna o Código da Reserva.
 * @return 
 */	
	public Integer getcodReservaVoo() {
	return codReservaVoo;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Código de Reserva.
 * @param codReservaVoo
 */	
	public void setcodReserva(Integer codReservaVoo) {
	this.codReservaVoo = codReservaVoo;
	}
/**
 * Método que retorna o número de reservas.
 * @return 
 */	
	public Integer getNumReservas() {
	return numReservas;
	}
/**
 * Método que permite o acesso de outras classes ao atributo Número de Reservas.
 * @param numReservas
 */	
	public void setNumReservas(Integer numReservas) {
	this.numReservas = numReservas;
	}
}
